name: Node.js & Docker Build CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.22'

    - name: Install Node Package
      run: npm install

    - name: Build Nodejs App
      run: npm run build --if-present

    - name: Test Nodejs App
      run: npm test
      env:
        CI: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ljwkeke/nodejs-example:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
